export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const SET_PERSONAL_PRODUCTS = 'SET_PERSONAL_PRODUCTS'

export const GET_USERS_PRODUCTS = 'GET_USERS_PRODUCTS';
export const GET_USERS_PRODUCTS_FAIL = 'GET_USERS_PRODUCTS_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'; 
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'; 
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';