export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCSES = 'ADD_PRODUCT_SUCCSES';

export const SET_PERSONAL_PRODUCTS = 'SET_PERSONAL_PRODUCTS'


export const DELETE_PRODUCT = 'DELETE_PRODUCT';
