export const SING_UP = 'SING_UP';


export const SING_IN = 'SING_IN';
export const SING_IN_FAIL ='SING_IN_FAIL';
export const SING_IN_SUCCESS ='SING_IN_SUCCESS';

export const SING_OUT = 'SING_OUT';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';
export const SING_OUT_SUCCESS = 'SING_OUT_SUCCESS';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_FAIL = 'ADD_INGREDIENT_FAIL'
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS'

export const EDIT_PERSONAL_INGREDIENT = 'EDIT_PERSONAL_INGREDIENT';
export const EDIT_PERSONAL_INGREDIENT_FAIL = 'EDIT_PERSONAL_INGREDIENT_FAIL';
export const EDIT_PERSONAL_INGREDIENT_SUCCESS = 'EDIT_PERSONAL_INGREDIENT_SUCCESS';

export const DELETE_PERSONAL_INGREDIENT = 'DELETE_PERSONAL_INGREDIENT';
export const DELETE_PERSONAL_INGREDIENT_FAIL = 'DELETE_PERSONAL_INGREDIENT_FAIL';
export const DELETE_PERSONAL_INGREDIENT_SUCCESS = 'DELETE_PERSONAL_INGREDIENT_SUCCESS';

export const GET_USER_INFORMATION = 'GET_USER_INFORMATION'; 
export const GET_USER_INFORMATION_FAIL = 'GET_USER_INFORMATION_FAIL';
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS'